server:
  port: 8080
  tomcat:
    uri-encoding: utf-8
  servlet:
    context-path:
    multipart:
      max-file-size: 20MB
      max-request-size: 50000MB


#文件上传相关
file:
  save-path: D:\images\
  save-port: 9001



spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/llt?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    username: root
    password: root

  redis:
      database: 0
      host: 127.0.0.1
      port: 6379
      password: root
      timeout: 1000
      jedis:
        pool:
          max-active: 8
          max-wait: -1
          max-idle: 8
          min-idle: 0

mybatis-plus:
  configuration:
    auto-mapping-behavior: full
  mapper-locations: classpath*:mapper/*Mapper.xml


springfox:
  documentation:
    enabled: true
#http:
#  #最大连接数
#  maxTotal: 1000
#  #并发数
#  defaultMaxPerRoute: 20
#  #创建连接的最长时间
#  connectTimeout: 5000
#  #从连接池中获取到连接的最长时间
#  connectionRequestTimeout: 5000
#  #数据传输的最长时间
#  socketTimeout: 5000
#  #提交请求前测试连接是否可用
#  staleConnectionCheckEnabled: true