server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/llt?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    username: root
    password: root

  redis:
      database: 0
      host: 127.0.0.1
      port: 6379
      password: root
      timeout: 1000
      jedis:
        pool:
          max-active: 8
          max-wait: -1
          max-idle: 8
          min-idle: 0

mybatis-plus:
  configuration:
    auto-mapping-behavior: full
  mapper-locations: classpath*:mapper/*Mapper.xml